version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/home/eric/docker/volumes/gitlab/config:/etc/gitlab'
      - '/home/eric/docker/volumes/gitlab/logs:/var/log/gitlab'
      - '/home/eric/docker/volumes/gitlab/data:/var/opt/gitlab'
