version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
#    env_file:
#      - db.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - MYSQL_HOST=ncdb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=example
      - NEXTCLOUD_ADMIN_USER=eric
      - NEXTCLOUD_ADMIN_PASSWORD=example
    volumes:
      - /opt/docker/volumes/nextcloud:/config
      - /media/cloud:/data
    ports:
      - 443:443

  ncdb:
    image: jsurf/rpi-mariadb
    container_name: ncdb
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/ncdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
#      - MYSQL_HOST=ncdb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=example
#    env_file:
#      - db.env

# Need to run the below command to add my DynIP domain to the trusted list
#docker exec -ti nextcloud sudo -u abc /config/www/nextcloud/occ config:system:set trusted_domains 1 --value=eweiss.servebeer.com
