version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - db.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/docker/volumes/nextcloud:/config
      - /media/orion/Titan/cloud:/data
    ports:
      - 443:443 

  ncdb:
#    image: mariadb
    image: jsurf/rpi-mariadb
    container_name: ncdb
    restart: unless-stopped
#    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/docker/volumes/ncdb:/var/lib/mysql
    environment:
      #- MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=ncdb
      - NEXTCLOUD_ADMIN_USER=eric
      - NEXTCLOUD_ADMIN_PASSWORD=example
#    env_file:
#      - db.env
