version: '2'
services:
  ncdb:
    image: mariadb
    container_name: ncdb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=example
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=ncdb
    env_file:
      - db.env
    volumes:
      - /media/orion/Seagate3.0/Repo/cloud:/var/www/html
    links:
      - ncdb
    depends_on:
      - ncdb

  ncweb:
    #image: nginx
    build: ./web
    container_name: ncweb
    restart: unless-stopped
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=localhost
    #volumes_from:
      #- app
    depends_on:
      - app
    ports:
      - 8079:80
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    container_name: ncproxy
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 4443:443
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    container_name: omgwtfssl
    restart: unless-stopped
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=servebeer.com
      - CA_SUBJECT=eric@eweiss.me
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.crt
    networks:
      - proxy-tier

volumes:
  ncdb:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
