version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /media/orion/Tosh3.0/Movies:/movies
      - /media/orion/Seagate3.0/Classics:/movies.classics
      - /media/orion/Venus/downloads:/downloads
      #- /opt/docker/volumes/radarr/movies:/movies
      #- /opt/docker/volumes/radarr/downloads:/downloads
    ports:
      - 7878:7878
