version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /media/orion/Titan/Movies:/movies
      - /media/orion/Titan/Classics:/movies.classics
      - /media/accretion/Downloads:/downloads
    ports:
      - 7878:7878
