version: '2'
services:
  cloud9:
    image: linuxserver/cloud9
    container_name: cloud9
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Detroit
      GITURL: https://github.com/linuxserver/docker-cloud9.git
    volumes:
      - /opt/docker/volumes/cloud9/code:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8000
