version: '2'
services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: America/Detroit
    ports:
      - 3306:3306

  node:
    image: node
    container_name: nodejs
    restart: unless-stopped
    user: "node"
    working_dir: /home/node/app
#    working_dir: /home/node/website
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
#      - ./website:/home/node/website
    ports:
      - 8081:8081
#    command: "sh -c 'npm i && npm run start'"
#    command: "sh -c 'npm i && npm run format'"
    command: "sh -c 'npm i && npm run dev'"
    links:
      - db

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
