version: '2'
services:
  flexget:
    image: cpoppema/docker-flexget
    container_name: flexget
    restart: unless-stopped
    environment:
      TZ: America/Detroit
      PGID: 1000
      PUID: 1000
#      WEB_SERVER: 'yes'
      WEB_PASSWD: FlexgetExample1!
#      TORRENT_PLUGIN: transmission
      TORRENT_PLUGIN: deluge-common
      FLEXGET_LOG_LEVEL: debug
    volumes:
      - /home/eric/docker/volumes/flexget/config:/config
      - /home/eric/docker/volumes/flexget/downloads:/downloads
    ports:
      - 5050:5050
