version: '2'
services:
  akaunting:
    image: sameersbn/akaunting:1.3.9
    container_name: akaunting
    restart: unless-stopped
    command: app:akaunting
    env_file:
      - ./.akaunting.example.env
    depends_on:
      - mysql
    volumes:
      - /opt/docker/volumes/akaunting/akaunting:/var/lib/akaunting

  mysql:
    image: sameersbn/mysql:5.7.24
    container_name: mysql_ak
    restart: unless-stopped
    env_file:
      - ./.akauntingdb.example.env
    volumes:
      - /opt/docker/volumes/akaunting/mysql:/var/lib/mysql

  nginx:
    image: sameersbn/akaunting:1.3.9
    container_name: nginx_ak
    restart: unless-stopped
    command: app:nginx
    environment:
      - AKAUNTING_PHP_FPM_HOST=akaunting
      - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
      - akaunting
    ports:
      - "10080:80"
