version: '2'
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Detroit
      TRANSMISSION_WEB_HOME: /combustion-release/
    volumes:
      - /opt/docker/volumes/transmission/config:/config
      #- /opt/docker/volumes/transmission/downloads:/downloads
      - /media/orion/Venus/downloads:/downloads
      - /opt/docker/volumes/transmission/watch:/watch
    ports:
      #- 9091:9091
      - 9090:9091
      - 51413:51413
      - 51413:51413/udp
