version: '2'
services:
  tsdb:
    image: mariadb
    container_name: tsdb
    restart: unless-stopped
    #environment:
    env_file:
      - ./.tsdb.env
    volumes:
      - /opt/docker/volumes/teamspeakdb:/var/lib/mysql

  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: unless-stopped
    #environment:
    env_file:
      - ./.ts.env
    volumes:
      - /opt/docker/volumes/teamspeak:/var/ts3server
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    depends_on: 
      - tsdb
    links:
      - tsdb
