version: "2"
services:
  photoshow:
    image: linuxserver/photoshow
    container_name: photoshow
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/docker/volumes/photoshow/config:/config
      - /opt/docker/volumes/photoshow/pictures:/Pictures:ro
      - /opt/docker/volumes/photoshow/Thumbs:/Thumbs
    ports:
      - 8383:80
