version: "2"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/lidarr/config:/config
      - /media/orion/Jupiter/FLAC:/music
      - /media/accretion/Downloads:/downloads
    ports:
      - 8686:8686
