---
addons:
  apt:
    packages:
    - docker-ce
    sources:
    - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
      key_url: 'https://download.docker.com/linux/ubuntu/gpg'

after_deploy:
  - docker buildx imagetools inspect "$DOCKER_IMAGE_ID_TAG"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_install:
  - docker run --privileged linuxkit/binfmt:v0.7

before_script:
  - docker version

deploy:
  - on:
      branch: master
    provider: script
    script: docker buildx build --platform "$PLATFORMS" -t "$DOCKER_IMAGE_ID_TAG" --push .
  - on:
      tags: true
    provider: script
    script: docker buildx build --platform "$PLATFORMS" -t "$DOCKER_IMAGE_ID":"$TRAVIS_TAG" --push .

dist: xenial

env:
  global:
    - DOCKER_BUILDX_DIR_PATH="${HOME}/.docker/cli-plugins"
    - DOCKER_BUILDX_PATH="${DOCKER_BUILDX_DIR_PATH}/docker-buildx"
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_IMAGE_ID=ferrarimarco/pxe
    - DOCKER_IMAGE_ID_TAG="$DOCKER_IMAGE_ID":latest
    - PLATFORMS="linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"

install:
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap

language: minimal

services:
  - docker

script:
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 -t "$DOCKER_IMAGE_ID_TAG" .
