version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000

