version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /home/eric/docker/volumes/sonarr/config:/config
      - /media/orion/Tosh3.0/TV:/tv
      - /media/orion/Jupiter/archive.tv:/tv.archive
      - /media/orion/Seagate3.0/Classic.tv:/tv.classic
      - /media/orion/Venus/downloads:/downloads
      #- /home/eric/docker/volumes/sonarr/tv:/tv
      #- /home/eric/docker/volumes/sonarr/downloads:/downloads
    ports:
      - 8989:8989
