version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/sonarr/config:/config
      - /media/orion/ColdSto/TV:/tv
      - /media/orion/ColdSto/archive.tv:/tv.archive
      - /media/orion/ColdSto/Classic.tv:/tv.classic
      - /media/accretion/Downloads:/downloads
    ports:
      - 8989:8989
