version: '2'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 1000
      GUID: 1000
      VERSION: docker
    volumes:
      - /opt/docker/volumes/plex/config:/config
      - /opt/docker/volumes/plex/transcode:/transcode
      - /media/orion/Titan/Movies:/data/movies
      - /media/orion/Titan/Classics:/data/movies.classics
      - /media/orion/ColdSto/archive.tv:/data/tv.archive
      - /media/orion/ColdSto/TV:/data/tv
      - /media/orion/ColdSto/Classic.tv:/data/tv.classic
    ports:
      - 32400:32400
