version: '2'
services:
  phpbbdb:
    image: bitnami/mariadb
    container_name: phpbbdb
    restart: unless-stopped
    env_file:
      - ./env/example.phpbbdb.env
    environment:
      TZ: America/Detroit
      MARIADB_DATABASE: bitnami_phpbb
      MARIADB_USER: bn_phpbb
      ALLOW_EMPTY_PASSWORD: 'yes'
    # Volume must be writable by other users o+w
    volumes:
      #- /home/eric/docker/volumes/phpbbdb:/bitnami
      - /opt/docker/volumes/phpbbdb:/bitnami

  phpbb:
    image: bitnami/phpbb
    container_name: phpbb
    restart: unless-stopped
    env_file:
      - ./env/example.phpbb.env
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_HOST: phpbbdb
    volumes:
      #- /home/eric/docker/volumes/phpbb:/bitnami
      - /opt/docker/volumes/phpbb:/bitnami
    ports:
      - 82:80
      - 4443:443
    links:
      - phpbbdb
    depends_on:
      - phpbbdb
