version: '2'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    environment:
      TZ: America/Detroit
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  netdata:
#    image: netdata/netdata
#    container_name: netdata
#    restart: unless-stopped
#    cap_add:
#      - SYS_PTRACE
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys/:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      TZ: America/Detroit
#    ports:
#      - 19999:19999
#    security_opt:
#      - apparmor:unconfined

  watchtower:
#    image: v2tec/watchtower:armhf-latest
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: unless-stopped
#    ports:
#      - 8081:8080

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/opt/docker/volumes/gitlab/config:/etc/gitlab'
      - '/opt/docker/volumes/gitlab/logs:/var/log/gitlab'
      - '/opt/docker/volumes/gitlab/data:/var/opt/gitlab'

  tsdb:
    image: mariadb
    container_name: tsdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: teamspeak
    volumes:
      - /opt/docker/volumes/teamspeakdb:/var/lib/mysql

  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: unless-stopped
    environment:
      TZ: America/Detroit
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: tsdb
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: example
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - /opt/docker/volumes/teamspeak:/var/ts3server
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    depends_on: 
      - tsdb
    links:
      - tsdb

  ncdb:
    image: mariadb
    container_name: ncdb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=example
    env_file:
      - /opt/docker/stacks/nextcloud/db.env

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=ncdb
    env_file:
      - /opt/docker/stacks/nextcloud/db.env
    volumes:
      - /media/orion/Seagate3.0/test/cloud:/var/www/html
    links:
      - ncdb
    depends_on:
      - ncdb

  ncweb:
    #image: nginx
    build: /opt/docker/stacks/nextcloud/web
    container_name: ncweb
    restart: unless-stopped
    volumes:
      - /opt/docker/stacks/nextcloud/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=localhost
    volumes_from:
      - app
    depends_on:
      - app
    ports:
      - 8079:80
    networks:
      - proxy-tier
      - default

  proxy:
    build: /opt/docker/stacks/nextcloud/proxy
    container_name: ncproxy
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 88:80
      - 4443:443
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    container_name: omgwtfssl
    restart: 'no'
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=servebeer.com
      - CA_SUBJECT=eric@eweiss.me
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.crt
    networks:
      - proxy-tier

  lancache-dns:
    image: lancachenet/lancache-dns
    container_name: lancache-dns
    restart: unless-stopped
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.1.106
    ports:
      - 192.168.1.106:53:53/udp

  monolithic:
    image: lancachenet/monolithic
    container_name: lancache
    restart: unless-stopped
    volumes:
      #- /opt/docker/volumes/lancache/cache:/data/cache
      - /media/orion/Seagate3.0/cache:/data/cache
      - /opt/docker/volumes/lancache/logs:/data/logs
    ports:
      - 192.168.1.106:80:80

  sniproxy:
    image: lancachenet/sniproxy
    container_name: sniproxy
    restart: unless-stopped
    ports:
      - 192.168.1.106:443:443

volumes:
  ncdb:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
