version: "2"
services:
# Monitoring Services
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    environment:
      TZ: America/Detroit
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # netdata:
  #   image: netdata/netdata
  #   container_name: netdata
  #   restart: unless-stopped
  #   cap_add:
  #     - SYS_PTRACE
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys/:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     TZ: America/Detroit
  #   ports:
  #     - 19999:19999
  #   security_opt:
  #     - apparmor:unconfined

  watchtower:
    image: v2tec/watchtower:armhf-latest
    #image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

# Ebook library
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/docker/volumes/calibre/config:/config
      - /media/orion/Seagate3.0/Repo/Documents/Books/epub.library:/books
    ports:
      - 8083:8083

# RSS Services
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/bazarr/config:/config
      - /media/orion/Tosh3.0/Movies:/movies
      - /media/orion/Tosh3.0/TV:/tv
      - /media/orion/Jupiter/archive.tv:/tv.archive
      - /media/orion/Seagate3.0/Classic.tv:/tv.classic
      - /media/orion/Seagate3.0/Classics:/movies.classics
    ports:
      - 6767:6767

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /media/orion/Tosh3.0/Movies:/movies
      - /media/orion/Seagate3.0/Classics:/movies/classics
      - /media/orion/Venus/downloads:/downloads
    ports:
      - 7878:7878

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/bazarr/config:/config
      #- /opt/docker/volumes/lidarr/music:/music
      - /media/orion/Seagate3.0/FLAC:/music
      - /opt/docker/volumes/lidarr/downloads:/downloads
    ports:
      - 8686:8686

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/sonarr/config:/config
      - /media/orion/Tosh3.0/TV:/tv
      - /media/orion/Jupiter/archive.tv:/tv.archive
      - /media/orion/Seagate3.0/Classic.tv:/tv.classic
      - /media/orion/Venus/downloads:/downloads
    ports:
      - 8989:8989

# Media Streaming
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 1000
      GUID: 1000
      VERSION: docker
    volumes:
      - /opt/docker/volumes/plex/config:/config
      - /media/orion/Tosh3.0/TV:/data/tv
      - /media/orion/Jupiter/archive.tv:/data/tv.archive
      - /media/orion/Seagate3.0/Classic.tv:/data/tv.classic
      - /media/orion/Tosh3.0/Movies:/data/movies
      - /media/orion/Seagate3.0/Classics:/data/movies.classics
      - /opt/docker/volumes/plex/transcode:/transcode
    ports:
      - 32400:32400

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Detroit
      BASE_URL: /ombi
    volumes:
      - /opt/docker/volumes/ombi/config:/config
    ports:
      - 3579:3579

# Development services
  cloud9:
    image: linuxserver/cloud9
    container_name: cloud9
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Detroit
      GITURL: https://github.com/linuxserver/docker-cloud9.git
    volumes:
      - /opt/docker:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8000
