version: "2"
services:
  db:
    container_name: webpage-db
    #image: mariadb
    #image: hypriot/rpi-mysql:latest
    image: jsurf/rpi-mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: "America/Detroit"
    command: --init-file /data/application/init.sql
    volumes:
      - /opt/docker/stacks/sql/init.sql:/data/application/init.sql
      #- /opt/docker/stacks/sql/example.sql:/data/application/init.sql

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

  php:
    container_name: php
    image: php:7-fpm
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - /opt/docker/stacks/webpage:/usr/share/nginx/html

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    environment:
      TZ: "America/Detroit"
    ports:
      - 81:80
    volumes:
      - /opt/docker/stacks/webpage:/usr/share/nginx/html
      - /opt/docker/stacks/webpage/site.conf:/etc/nginx/conf.d/default.conf
    links:
      -  php
