version: '2'
services:
  goaccess:
#    image: allinurl/goaccess
    image: hectormolinero/goaccess
    container_name: goaccess
    restart: unless-stopped
    ports:
      - 7890:7890
    volumes:
      - /opt/docker/volumes/goaccess/data:/srv/data:ro
      #- /opt/docker/volumes/nginx/logs:/srv/logs:ro
      - /opt/docker/volumes/goaccess/html:/srv/report:rw
