version: '2'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: ovpn
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/openvpn:/etc/openvpn
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
