version: "2"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - /opt/docker/volumes/bazarr/config:/config
      #- /home/eric/docker/volumes/bazarr/movies:/movies
      #- /home/eric/docker/volumes/bazarr/tv:/tv
      - /media/orion/Tosh3.0/Movies:/movies
      - /media/orion/Tosh3.0/TV:/tv
      - /media/orion/Jupiter/archive.tv:/tv.archive
      - /media/orion/Seagate3.0/Classic.tv:/tv.classic
      - /media/orion/Seagate3.0/Classics:/movies.classics
      
    ports:
      - 6767:6767
