version: '2'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    environment:
      TZ: America/Detroit
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  netdata:
#    image: netdata/netdata
#    container_name: netdata
#    restart: unless-stopped
#    cap_add:
#      - SYS_PTRACE
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys/:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      TZ: America/Detroit
#    ports:
#      - 19999:19999
#    security_opt:
#      - apparmor:unconfined

  watchtower:
#    image: v2tec/watchtower:armhf-latest
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: unless-stopped
#    ports:
#      - 8081:8080
